# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csample.proto\x12\x06sample\")\n\x0cHelloMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"!\n\x0cReplyMessage\x12\x11\n\treply_msg\x18\x01 \x01(\t2J\n\rSampleService\x12\x39\n\x0bHelloServer\x12\x14.sample.HelloMessage\x1a\x14.sample.ReplyMessageb\x06proto3'
)




_HELLOMESSAGE = _descriptor.Descriptor(
  name='HelloMessage',
  full_name='sample.HelloMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='sample.HelloMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='sample.HelloMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=65,
)


_REPLYMESSAGE = _descriptor.Descriptor(
  name='ReplyMessage',
  full_name='sample.ReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_msg', full_name='sample.ReplyMessage.reply_msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['HelloMessage'] = _HELLOMESSAGE
DESCRIPTOR.message_types_by_name['ReplyMessage'] = _REPLYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloMessage = _reflection.GeneratedProtocolMessageType('HelloMessage', (_message.Message,), {
  'DESCRIPTOR' : _HELLOMESSAGE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.HelloMessage)
  })
_sym_db.RegisterMessage(HelloMessage)

ReplyMessage = _reflection.GeneratedProtocolMessageType('ReplyMessage', (_message.Message,), {
  'DESCRIPTOR' : _REPLYMESSAGE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.ReplyMessage)
  })
_sym_db.RegisterMessage(ReplyMessage)



_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='sample.SampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloServer',
    full_name='sample.SampleService.HelloServer',
    index=0,
    containing_service=None,
    input_type=_HELLOMESSAGE,
    output_type=_REPLYMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
