# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/zebra1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/zebra1.proto',
  package='zebra1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15protobuf/zebra1.proto\x12\x06zebra1\"\x1b\n\x07Message\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t2>\n\rPreProcessing\x12-\n\tThreshold\x12\x0f.zebra1.Message\x1a\x0f.zebra1.Messageb\x06proto3'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='zebra1.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='zebra1.Message.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'protobuf.zebra1_pb2'
  # @@protoc_insertion_point(class_scope:zebra1.Message)
  })
_sym_db.RegisterMessage(Message)



_PREPROCESSING = _descriptor.ServiceDescriptor(
  name='PreProcessing',
  full_name='zebra1.PreProcessing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=62,
  serialized_end=124,
  methods=[
  _descriptor.MethodDescriptor(
    name='Threshold',
    full_name='zebra1.PreProcessing.Threshold',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREPROCESSING)

DESCRIPTOR.services_by_name['PreProcessing'] = _PREPROCESSING

# @@protoc_insertion_point(module_scope)
