# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobuf import zebra1_pb2 as protobuf_dot_zebra1__pb2


class PreProcessingStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Threshold = channel.unary_unary(
                '/zebra1.PreProcessing/Threshold',
                request_serializer=protobuf_dot_zebra1__pb2.Message.SerializeToString,
                response_deserializer=protobuf_dot_zebra1__pb2.Message.FromString,
                )


class PreProcessingServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Threshold(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Threshold': grpc.unary_unary_rpc_method_handler(
                    servicer.Threshold,
                    request_deserializer=protobuf_dot_zebra1__pb2.Message.FromString,
                    response_serializer=protobuf_dot_zebra1__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zebra1.PreProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PreProcessing(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Threshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zebra1.PreProcessing/Threshold',
            protobuf_dot_zebra1__pb2.Message.SerializeToString,
            protobuf_dot_zebra1__pb2.Message.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
