# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobuf import zebra_pb2 as protobuf_dot_zebra__pb2


class Zebra1ServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/zebra.Zebra1Service/Recognize',
                request_serializer=protobuf_dot_zebra__pb2.ReqMessage.SerializeToString,
                response_deserializer=protobuf_dot_zebra__pb2.ResMessage.FromString,
                )


class Zebra1ServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Zebra1ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=protobuf_dot_zebra__pb2.ReqMessage.FromString,
                    response_serializer=protobuf_dot_zebra__pb2.ResMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zebra.Zebra1Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Zebra1Service(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zebra.Zebra1Service/Recognize',
            protobuf_dot_zebra__pb2.ReqMessage.SerializeToString,
            protobuf_dot_zebra__pb2.ResMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class Zebra2ServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/zebra.Zebra2Service/Inference',
                request_serializer=protobuf_dot_zebra__pb2.ReqMessage.SerializeToString,
                response_deserializer=protobuf_dot_zebra__pb2.ResMessage.FromString,
                )


class Zebra2ServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Zebra2ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=protobuf_dot_zebra__pb2.ReqMessage.FromString,
                    response_serializer=protobuf_dot_zebra__pb2.ResMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zebra.Zebra2Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Zebra2Service(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zebra.Zebra2Service/Inference',
            protobuf_dot_zebra__pb2.ReqMessage.SerializeToString,
            protobuf_dot_zebra__pb2.ResMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
