# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobuf import zebra2_pb2 as protobuf_dot_zebra2__pb2


class RecognizeStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/zebra2.Recognize/Predict',
                request_serializer=protobuf_dot_zebra2__pb2.ReqMessage.SerializeToString,
                response_deserializer=protobuf_dot_zebra2__pb2.ResMessage.FromString,
                )


class RecognizeServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognizeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=protobuf_dot_zebra2__pb2.ReqMessage.FromString,
                    response_serializer=protobuf_dot_zebra2__pb2.ResMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zebra2.Recognize', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recognize(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zebra2.Recognize/Predict',
            protobuf_dot_zebra2__pb2.ReqMessage.SerializeToString,
            protobuf_dot_zebra2__pb2.ResMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
