# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/zebra2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/zebra2.proto',
  package='zebra2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15protobuf/zebra2.proto\x12\x06zebra2\"\x1e\n\nReqMessage\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x1c\n\nResMessage\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32>\n\tRecognize\x12\x31\n\x07Predict\x12\x12.zebra2.ReqMessage\x1a\x12.zebra2.ResMessageb\x06proto3'
)




_REQMESSAGE = _descriptor.Descriptor(
  name='ReqMessage',
  full_name='zebra2.ReqMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='zebra2.ReqMessage.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=63,
)


_RESMESSAGE = _descriptor.Descriptor(
  name='ResMessage',
  full_name='zebra2.ResMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='zebra2.ResMessage.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['ReqMessage'] = _REQMESSAGE
DESCRIPTOR.message_types_by_name['ResMessage'] = _RESMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqMessage = _reflection.GeneratedProtocolMessageType('ReqMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQMESSAGE,
  '__module__' : 'protobuf.zebra2_pb2'
  # @@protoc_insertion_point(class_scope:zebra2.ReqMessage)
  })
_sym_db.RegisterMessage(ReqMessage)

ResMessage = _reflection.GeneratedProtocolMessageType('ResMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESMESSAGE,
  '__module__' : 'protobuf.zebra2_pb2'
  # @@protoc_insertion_point(class_scope:zebra2.ResMessage)
  })
_sym_db.RegisterMessage(ResMessage)



_RECOGNIZE = _descriptor.ServiceDescriptor(
  name='Recognize',
  full_name='zebra2.Recognize',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=95,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='zebra2.Recognize.Predict',
    index=0,
    containing_service=None,
    input_type=_REQMESSAGE,
    output_type=_RESMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOGNIZE)

DESCRIPTOR.services_by_name['Recognize'] = _RECOGNIZE

# @@protoc_insertion_point(module_scope)
